apiVersion: apps/v1
kind: Deployment
metadata:
  name: diff-pics
  labels:
    app: diff-pics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diff-pics
  template:
    metadata:
      labels:
        app: diff-pics
    spec:
      containers:
        - name: diff-pics
          image: gcr.io/fugi-tech/diff-pics
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: diff-pics
  labels:
    app: diff-pics
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app: diff-pics
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: diff-pics
spec:
  rules:
    - host: diff.pics
      http:
        paths:
          - path: /
            backend:
              serviceName: diff-pics
              servicePort: web
          - path: /check_images
            backend:
              serviceName: diff-pics-check-images
              servicePort: 8080
          - path: /create_comparison
            backend:
              serviceName: diff-pics-create-comparison
              servicePort: 8080
          - path: /download
            backend:
              serviceName: diff-pics-download
              servicePort: 8080
          - path: /upload
            backend:
              serviceName: diff-pics-upload
              servicePort: 8080
          - path: /{k:[-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z][-_0-9A-Za-z]+}
            backend:
              serviceName: diff-pics-comparison
              servicePort: 8080
