apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: cce62dc4-cf60-478e-b89f-55f6f541a76e
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: diff-pics-comparison
    type: name
  host: diff.pics
  method: GET
  relativeurl: /{key:............+}/{index}
